project:
  type: website

website:
  title: "Himanshu Poswal"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Himanshu-code1960
format:
  html:
    highlight-style: monokai
    theme:
      - cosmo
      - brand
    css: styles.css



